phases:
- phase: PreBuild
  steps:
  - task: Npm@1
    displayName: Npm Install
    inputs:
      command: install
  - task: Npm@1
    displayName: Ng Lint
    inputs:
      command: custom
      customCommand: run ng lint
- phase: Build
  dependsOn: PreBuild
  steps:
  - task: Npm@1
    displayName: Npm Install
    inputs:
      command: install
  - task: Npm@1
    displayName: Ng Build Production
    inputs:
      command: custom
      customCommand: "run ng build --prod"
  - task: ArchiveFiles@2
    displayName: Package Artifacts
    inputs:
      rootFolderOrFile: dist
      includeRootFolder: false
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      artifactName: drop
      artifactType: "Visual Studio Team Services/TFS"
